name: pixez
description: A new Flutter project.

publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.9.79+492

environment:
  sdk: ">=3.6.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  crypto: ^3.0.7
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  share_plus: ^10.1.1
  permission_handler: ^11.3.1
  archive: ^4.0.7
  url_launcher: ^6.3.3
  bot_toast: ^4.1.3
  package_info_plus: ^8.1.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  in_app_purchase: ^3.1.11
  flutter_widget_from_html: ^0.16.0
  device_info_plus: ^11.1.0
  flutter_displaymode: ^0.7.0
  receive_sharing_intent: ^1.8.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  waterfall_flow: ^3.1.1
  animations: ^2.0.11
  font_awesome_flutter: ^10.6.0
  json_annotation: ^4.9.0
  badges: ^3.1.2
  image_picker: ^1.1.2
  image_gallery_saver:
    git:
      url: https://github.com/bgli100/flutter_image_gallery_saver_ohos.git
      ref: master
  file_picker_ohos:
    git:
      url: https://github.com/bgli100/flutter_file_picker_ohos.git
      ref: master
  video_player:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_packages.git
      path: packages/video_player/video_player
      ref: br_video_player-v2.10.0_ohos
  intl: any
  quiver: ^3.2.2
  flutter_inappwebview: ^6.1.5
  dio_cache_interceptor: ^4.0.5
  photo_view: ^0.15.0
  image: ^4.5.4
  easy_refresh: ^3.4.0
  sqflite: ^2.4.2
  dynamic_color:
    git:
      url: https://github.com/hasali19/material-foundation-flutter-packages.git
      path: packages/dynamic_color
      ref: main
  # Desktop Support
  flutter_acrylic: ^1.1.4
  window_manager: ^0.4.3
  rhttp:
    path: ../rhttp/rhttp/
  dio_compatibility_layer: ^0.1.0
  flutter_cache_manager_dio: ^4.0.0
  file_picker: ^10.3.3
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0
  sqflite_common_ffi: ^2.4.0
  msix: ^3.16.9
  analyzer: ^6.4.1
  build_runner: 2.4.15
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.4.4

dependency_overrides:
  receive_sharing_intent:
    git:
      url: https://gitcode.com/openharmony-sig/fluttertpc_receive_sharing_intent.git
      ref: br_v1.8.1_ohos
  animations:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_packages.git
      path: packages/animations
  in_app_purchase:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_packages.git
      path: packages/in_app_purchase/in_app_purchase
  path_provider:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_packages.git
      path: packages/path_provider/path_provider
  flutter_inappwebview:	
    git:
      url: https://gitcode.com/openharmony-sig/flutter_inappwebview.git
      path: flutter_inappwebview
  permission_handler:
    git: 
      url: https://gitcode.com/openharmony-sig/flutter_permission_handler.git
      path: permission_handler
      ref: br_permission_handler_v11.3.1_ohos
  share_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/share_plus/share_plus
      ref: br_share_plus-v10.1.1_ohos
  battery_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/battery_plus/battery_plus
  url_launcher:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_packages.git
      path: packages/url_launcher/url_launcher
  shared_preferences:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_packages.git
      path: packages/shared_preferences/shared_preferences
  device_info_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/device_info_plus/device_info_plus
      ref: br_device_info_plus-v11.1.0_ohos
  package_info_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/package_info_plus/package_info_plus
      ref: br_package_info_plus-v8.1.0_ohos
  connectivity_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/connectivity_plus/connectivity_plus
  network_info_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/network_info_plus/network_info_plus
  file_selector:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_packages.git
      path: packages/file_selector/file_selector
  image_picker:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_packages.git
      path: packages/image_picker/image_picker
  flutter_widget_from_html:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_widget_from_html.git
      path: packages/enhanced
      ref: br_v0.15.2_ohos
  fwfh_chewie:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_widget_from_html.git
      path: packages/fwfh_chewie
      ref: br_v0.15.2_ohos
  sqflite:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_sqflite.git
      path: sqflite
      ref: br_v2.4.1_ohos
  sqflite_common:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_sqflite.git
      path: sqflite_common
      ref: br_v2.4.1_ohos
  sqflite_platform_interface:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_sqflite.git
      path: sqflite_platform_interface
      ref: br_v2.4.1_ohos
  sqflite_ohos:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_sqflite.git
      path: sqflite_ohos
      ref: br_v2.4.1_ohos
  video_player:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/video_player/video_player

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/host.json
    - assets/emojis/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  generate: true

msix_config:
  display_name: Pixez
  publisher_display_name: Perol_Notsfsssf
  identity_name: com.perol.pixez
  logo_path: .\windows\runner\resources\ic_launcher-msstore.png
  trim_logo: false
  capabilities: internetClient, picturesLibrary
  languages: en-us, es-es, ja-jp, ko-kr, ru-ru, tr-tr, zh-cn, zh-tw
  protocol_activation: pixiv, pixez
  app_uri_handler_hosts: i.pximg.net, pixiv.me, pixivision.net
  execution_alias: pixez
  install_certificate: false
  store: false
  publisher: CN=Notsfsssf, C=CN
